version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/ConsoleAppTemplate/Content"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dotnet"

  - package-ecosystem: "nuget"
    directory: "/src/ConsoleAppTemplate"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dotnet"

  - package-ecosystem: "nuget"
    directory: "/src/EtlSubCommandTemplate"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dotnet"

  - package-ecosystem: "nuget"
    directory: "/src/SubCommandTemplate"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dotnet"
