name: Security Scanning

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

jobs:
  code-scanning:
    name: Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: security

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Secret Scanning
        uses: github/secret-scanning-action@v1

  dependency-scanning:
    name: Dependency Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot
        uses: dependabot/dependabot-core-action@v1
        with:
          directory: /
          package-manager: npm_and_yarn
          update-type: security
